package com.likes.common.mybatis.mapper.pay;


import com.likes.common.mybatis.entity.pay.MerchantPaymentChannel;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MerchantPaymentChannelMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated
     */
    int insert(MerchantPaymentChannel merchantPaymentChannel);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MerchantPaymentChannel merchantPaymentChannel);

    MerchantPaymentChannel getMerchantPaymentChannel(@Param("merchatAcct") String merchatAcct, @Param("payChanCode") String payChanCode);
    List<MerchantPaymentChannel> getMerchantPaymentChannelAll(@Param("merchatAcct") String merchatAcct);
}