package com.likes.common.mybatis.mapper.pay;

import com.likes.common.mybatis.entity.pay.PaymentOrderFlow;
import org.apache.ibatis.annotations.Param;

public interface PaymentOrderFlowMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated
     */
    int insert(PaymentOrderFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PaymentOrderFlow record);

    PaymentOrderFlow getPaymentOrderFlow(@Param("merchatAcct") String merchatAcct, @Param("payChanCode") String payChanCode, @Param("merOrderNo") String merOrderNo);

}